name: Bicep -> ARM

on:
    push:
        branches: [main]
        paths:
            # only run if bicep file changed
            - 'Environments/*.bicep'
            - 'Environments/modules/**/*.bicep'
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        permissions:
            contents: write
        
        steps:
        - uses: actions/checkout@v3
        
        - name: Build Bicep -> ARM
          shell: python
          run: |
                import os
                import subprocess
                
                from pathlib import Path

                def compile_bicep_to_arm(bicep_file_path, output_dir):
                    arm_file_path = os.path.join(output_dir, 'az_deploy.json')
                    cmd = f'az bicep build --file {bicep_file_path} --outfile {arm_file_path}'
                
                    try:
                        subprocess.run(cmd, check=True, shell=True)
                        print(f'Successfully compiled {bicep_file_path} to {arm_file_path}')
                    except subprocess.CalledProcessError as e:
                        print(f'Failed to compile {bicep_file_path} to ARM template. Error: {e}')
                
                def main():
                    bicep_file_path = Path.cwd() / 'Environments' / 'main.bicep'
                    output_dir = Path.cwd() / 'Environments' 
                    compile_bicep_to_arm(bicep_file_path, output_dir)
                
                if __name__ == '__main__':
                        main()
        
        - name: Commit changes
          run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -am "Rebuild ARM templates"
            git pull
            git push

        

