name: Bicep -> ARM

on:
    push:
        branches: ['*']
        paths:
            # only run if bicep file changed
            - 'Environments/*.bicep'
            - 'Environments/modules/**/*.bicep'
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        permissions:
            contents: write
        
        steps:
        - uses: actions/checkout@v3
        
        - name: Build Bicep -> ARM
          run:  python ./tools/build-arm.py
        
        - name: Commit changes
          run: |
                git config --global user.name "TakumiSeo"
                git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                git add ./az_deploy.json ./az_deploy.parameters.json
                git commit -am "Rebuild ARM templates"
                git push

        

